//! `fleetgen.rs` — derive a candidate `fleet.toml` from the live daemon set.
//!
//! `rollout fleet-gen` inspects what is actually running (via `binstale scan
//! --format json`) and correlates each daemon's install path against the
//! `~/.config/systemd/user/*.service` map to discover the owning unit. It
//! then writes a `fleet.toml.proposed` file that can be reviewed and accepted
//! with a single `mv` command.
//!
//! **Safety invariant**: this module never writes to `fleet.toml` itself.
//! Only the `--out` path (default `.proposed`) is written.

use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};
use std::process::Command;

use regex::Regex;
use serde::Deserialize;

use crate::error::RolloutError;
use crate::install::{find_unit_for_dest, home_dir};

// ── binstale full entry (fleet-gen needs source_repo) ────────────────────────

/// Full binstale entry including `source_repo` (not present in the stale-only
/// scan struct used by `scan.rs`).
#[derive(Debug, Clone, Deserialize)]
struct FullEntry {
    comm: String,
    exe_path: String,
    source_repo: Option<String>,
    /// Verdict; fleet-gen considers ALL entries (fresh + stale).
    #[allow(dead_code)]
    verdict: String,
}

// ── public entry point ────────────────────────────────────────────────────────

/// Arguments for `rollout fleet-gen`.
#[derive(Debug, Clone)]
pub(crate) struct FleetGenArgs {
    /// Write the proposed config to this path.
    /// Default: `~/.config/rollout/fleet.toml.proposed`.
    pub out: Option<PathBuf>,
    /// Only include daemons whose `comm` matches this regex.
    pub match_regex: Option<String>,
}

/// Run the `fleet-gen` subcommand.
///
/// # Errors
///
/// Returns an error if binstale cannot be invoked, the output path cannot
/// be created, or the TOML cannot be written.
pub(crate) fn run_fleet_gen(args: &FleetGenArgs) -> Result<(), RolloutError> {
    let home = home_dir()?;

    // Resolve the output path.
    let out_path = match &args.out {
        Some(p) => expand_tilde_path(p, &home),
        None => home
            .join(".config/rollout/fleet.toml.proposed"),
    };

    // Safety: refuse to write to fleet.toml directly.
    let fleet_toml = home.join(".config/rollout/fleet.toml");
    if out_path == fleet_toml {
        return Err(RolloutError::FleetConfig(
            "fleet-gen refuses to write directly to fleet.toml; use --out to specify \
             a different path, or omit --out to use fleet.toml.proposed"
                .to_owned(),
        ));
    }

    // Compile optional match regex.
    let match_re: Option<Regex> = match &args.match_regex {
        Some(pat) => Some(
            Regex::new(pat).map_err(|e| {
                RolloutError::FleetConfig(format!("invalid --match regex {pat:?}: {e}"))
            })?,
        ),
        None => None,
    };

    // Invoke binstale to get ALL entries (fresh + stale).
    let entries = scan_all_entries(match_re.as_ref())?;

    // Build the proposed TOML content.
    let mut toml_buf = String::new();
    toml_buf.push_str("# fleet.toml.proposed — generated by rollout fleet-gen\n");
    toml_buf.push_str("# Review this file, then: mv ~/.config/rollout/fleet.toml.proposed \\\n");
    toml_buf.push_str("#   ~/.config/rollout/fleet.toml\n\n");

    let mut matched = 0usize;
    let mut skipped: Vec<String> = Vec::new();

    for entry in &entries {
        let exe = Path::new(&entry.exe_path);
        let unit = find_unit_for_dest(exe)?;

        match unit {
            None => {
                skipped.push(entry.comm.clone());
            }
            Some(ref unit_name) => {
                let install_cmd = derive_install_cmd(&entry.comm, exe, &home);
                let launch_cmd = format!("systemctl --user restart {unit_name}");
                let repo_line = entry.source_repo.as_deref().map(|r| {
                    format!("repo = \"{r}\"\n")
                });

                writeln!(toml_buf, "[[daemon]]").ok();
                writeln!(toml_buf, "name = \"{}\"", entry.comm).ok();
                if let Some(rl) = repo_line {
                    write!(toml_buf, "{rl}").ok();
                }
                writeln!(toml_buf, "build_cmd = \"cargo build --release\"").ok();
                writeln!(toml_buf, "install_cmd = \"{install_cmd}\"").ok();
                writeln!(toml_buf, "launch_cmd = \"{launch_cmd}\"").ok();
                writeln!(toml_buf, "unit = \"{unit_name}\"").ok();
                writeln!(toml_buf).ok();

                matched += 1;
            }
        }
    }

    // Append skipped comments.
    for name in &skipped {
        writeln!(toml_buf, "# skipped: no systemd unit for {name}").ok();
    }
    if !skipped.is_empty() {
        writeln!(toml_buf).ok();
    }

    // Create output dir if absent.
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| {
            RolloutError::Io(std::io::Error::new(
                e.kind(),
                format!("create dir {}: {e}", parent.display()),
            ))
        })?;
    }

    // If fleet.toml already exists, print a unified diff to stdout.
    if fleet_toml.exists() {
        let existing = std::fs::read_to_string(&fleet_toml)
            .map_err(|e| RolloutError::FleetConfig(format!("read fleet.toml: {e}")))?;
        print_unified_diff(&existing, &toml_buf, "fleet.toml", "fleet.toml.proposed");
    }

    // Write the proposed file.
    std::fs::write(&out_path, &toml_buf).map_err(|e| {
        RolloutError::Io(std::io::Error::new(
            e.kind(),
            format!("write {}: {e}", out_path.display()),
        ))
    })?;

    println!(
        "rollout fleet-gen: wrote {matched} daemon(s) to {}",
        out_path.display()
    );
    if !skipped.is_empty() {
        println!(
            "rollout fleet-gen: skipped {} daemon(s) with no systemd unit: {}",
            skipped.len(),
            skipped.join(", ")
        );
    }
    println!(
        "rollout fleet-gen: to accept, run:\n  mv {} {}",
        out_path.display(),
        fleet_toml.display()
    );

    Ok(())
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// Invoke `binstale scan --format json` (with optional `--match`) and return
/// ALL entries (fresh + stale), deduplicated by comm name.
fn scan_all_entries(match_re: Option<&Regex>) -> Result<Vec<FullEntry>, RolloutError> {
    let mut cmd = Command::new("binstale");
    cmd.arg("scan").arg("--format").arg("json");
    let out = cmd.output().map_err(|e| {
        RolloutError::BinstaleScanFailed(format!("binstale not found: {e}"))
    })?;
    if !out.status.success() && out.stdout.is_empty() {
        return Err(RolloutError::BinstaleScanFailed(
            String::from_utf8_lossy(&out.stderr).into_owned(),
        ));
    }

    let json = String::from_utf8_lossy(&out.stdout);
    let all: Vec<FullEntry> = serde_json::from_str(&json).map_err(RolloutError::Json)?;

    // Apply optional regex filter + deduplicate by comm in one pass.
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    let deduped: Vec<FullEntry> = all
        .into_iter()
        .filter(|e| {
            let re_ok = match_re.is_none_or(|re| re.is_match(&e.comm));
            re_ok && seen.insert(e.comm.clone())
        })
        .collect();

    Ok(deduped)
}

/// Derive the `install_cmd` from the exe destination path.
///
/// - `~/.cargo/bin/<name>` → `cargo install --path . --root ~/.cargo`
/// - `~/.local/bin/<name>` (or anything else) → `cargo install --path . --root ~/.local`
fn derive_install_cmd(comm: &str, exe: &Path, home: &Path) -> String {
    let cargo_bin = home.join(".cargo/bin").join(comm);
    let local_bin = home.join(".local/bin").join(comm);

    // Compare canonical paths to handle symlinks.
    let exe_c = std::fs::canonicalize(exe).unwrap_or_else(|_| exe.to_owned());
    let cargo_c = std::fs::canonicalize(&cargo_bin).unwrap_or(cargo_bin);
    let local_c = std::fs::canonicalize(&local_bin).unwrap_or(local_bin);

    if exe_c == cargo_c {
        "cargo install --path . --root ~/.cargo".to_owned()
    } else if exe_c == local_c {
        "cargo install --path . --root ~/.local".to_owned()
    } else {
        // Fall back based on path prefix.
        let exe_str = exe.to_string_lossy();
        let home_str = home.to_string_lossy();
        if exe_str.contains(&format!("{home_str}/.cargo/")) {
            "cargo install --path . --root ~/.cargo".to_owned()
        } else {
            "cargo install --path . --root ~/.local".to_owned()
        }
    }
}

/// Expand a leading `~` in a path using the given home directory.
fn expand_tilde_path(p: &Path, home: &Path) -> PathBuf {
    let s = p.to_string_lossy();
    if let Some(rest) = s.strip_prefix("~/") {
        home.join(rest)
    } else if s == "~" {
        home.to_owned()
    } else {
        p.to_owned()
    }
}

/// Print a simple unified diff of `old` vs `new` to stdout.
///
/// Uses the standard `diff -u` shell command when available; falls back to a
/// minimal "old vs new" summary if `diff` is not found.
fn print_unified_diff(old: &str, new: &str, old_name: &str, new_name: &str) {
    use std::io::Write as IoWrite;

    // Write both sides to temp files and run `diff -u`.
    let old_tmp = std::env::temp_dir().join("rollout-fleet-gen-old.toml");
    let new_tmp = std::env::temp_dir().join("rollout-fleet-gen-new.toml");

    if std::fs::write(&old_tmp, old).is_ok() && std::fs::write(&new_tmp, new).is_ok() {
        let result = Command::new("diff")
            .arg("-u")
            .arg(format!("--label={old_name}"))
            .arg(format!("--label={new_name}"))
            .arg(&old_tmp)
            .arg(&new_tmp)
            .output();
        // `diff` exits 1 when there are differences; that's expected.
        // Use if-let so the Err branch cleanup is the else arm.
        if let Ok(out) = result {
            let _ = std::io::stdout().write_all(&out.stdout);
            if out.stdout.is_empty() {
                println!("# fleet-gen: proposed is identical to existing fleet.toml");
            }
            let _ = std::fs::remove_file(&old_tmp);
            let _ = std::fs::remove_file(&new_tmp);
            return;
        }
        let _ = std::fs::remove_file(&old_tmp);
        let _ = std::fs::remove_file(&new_tmp);
    }

    // Fallback: print a brief note.
    println!("# fleet-gen: existing fleet.toml differs from proposed ({old_name} → {new_name})");
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// AC1: fleet-gen --help subcommand is wired (tested via CLI argument
    /// parsing in cli.rs; here we verify the args struct derives correctly).
    #[test]
    fn fleet_gen_args_default_out_is_none() {
        let args = FleetGenArgs { out: None, match_regex: None };
        assert!(args.out.is_none());
        assert!(args.match_regex.is_none());
    }

    /// AC3: derive_install_cmd returns cargo root for .cargo/bin paths.
    #[test]
    fn derive_install_cmd_cargo_bin() {
        let home = PathBuf::from("/home/testuser");
        let exe = PathBuf::from("/home/testuser/.cargo/bin/wm-audio");
        let cmd = derive_install_cmd("wm-audio", &exe, &home);
        assert_eq!(cmd, "cargo install --path . --root ~/.cargo");
    }

    /// AC3: derive_install_cmd returns local root for .local/bin paths.
    #[test]
    fn derive_install_cmd_local_bin() {
        let home = PathBuf::from("/home/testuser");
        let exe = PathBuf::from("/home/testuser/.local/bin/recalld");
        let cmd = derive_install_cmd("recalld", &exe, &home);
        assert_eq!(cmd, "cargo install --path . --root ~/.local");
    }

    /// AC4: run_fleet_gen refuses to write directly to fleet.toml.
    #[test]
    fn fleet_gen_refuses_fleet_toml_out() {
        let home = home_dir().unwrap_or_else(|_| PathBuf::from("/tmp"));
        let fleet_toml = home.join(".config/rollout/fleet.toml");
        let args = FleetGenArgs {
            out: Some(fleet_toml),
            match_regex: None,
        };
        // Should error immediately without calling binstale.
        let result = run_fleet_gen(&args);
        assert!(result.is_err(), "fleet-gen must refuse to write fleet.toml");
        let msg = format!("{}", result.unwrap_err());
        assert!(
            msg.contains("fleet-gen refuses"),
            "error message should mention refusal: {msg}"
        );
    }

    /// AC4: safety invariant — fleet.toml is not touched when it pre-exists with
    /// sentinel content.
    #[test]
    fn fleet_gen_does_not_overwrite_fleet_toml() {
        let tmp = TempDir::new().expect("tempdir");
        let fleet_toml = tmp.path().join("fleet.toml");
        let proposed = tmp.path().join("fleet.toml.proposed");

        // Write sentinel content to fleet.toml.
        std::fs::write(&fleet_toml, b"# sentinel content\n").expect("write sentinel");

        // run_fleet_gen with --out pointing to proposed should never touch fleet.toml.
        // We can't easily mock binstale here, so we just verify the path logic:
        // if out_path != fleet_toml, the guard passes and only out_path is written.
        assert_ne!(proposed, fleet_toml, "proposed path must differ from fleet.toml");

        // Sentinel must be unchanged.
        let content = std::fs::read_to_string(&fleet_toml).expect("read sentinel");
        assert_eq!(content, "# sentinel content\n");
    }

    /// AC2: each generated block includes the required fields.
    #[test]
    fn generated_block_has_required_fields() {
        // Simulate the TOML generation logic directly without calling binstale.
        let mut buf = String::new();
        let unit_name = "wm-audio.service";
        let comm = "wm-audio";
        let repo = "/home/jsy/wintermute/wintermute-audio";
        let install_cmd = "cargo install --path . --root ~/.cargo";
        let launch_cmd = format!("systemctl --user restart {unit_name}");

        writeln!(buf, "[[daemon]]").ok();
        writeln!(buf, "name = \"{comm}\"").ok();
        writeln!(buf, "repo = \"{repo}\"").ok();
        writeln!(buf, "build_cmd = \"cargo build --release\"").ok();
        writeln!(buf, "install_cmd = \"{install_cmd}\"").ok();
        writeln!(buf, "launch_cmd = \"{launch_cmd}\"").ok();
        writeln!(buf, "unit = \"{unit_name}\"").ok();

        for field in &["name", "repo", "install_cmd", "launch_cmd", "unit"] {
            assert!(buf.contains(field), "AC2: generated block must contain field {field}");
        }

        // Verify the block parses as valid TOML with the DaemonRecipe schema.
        // We wrap it in a table to match the fleet.toml format.
        let parsed: toml::Value = toml::from_str(&buf).expect("generated TOML must be valid");
        let daemons = parsed["daemon"].as_array().expect("[[daemon]] array");
        assert_eq!(daemons.len(), 1);
        assert_eq!(daemons[0]["name"].as_str(), Some(comm));
        assert_eq!(daemons[0]["unit"].as_str(), Some(unit_name));
    }

    /// AC6: daemons with no systemd unit get a comment line, not a [[daemon]] block.
    #[test]
    fn skipped_daemon_gets_comment_not_block() {
        let skipped = vec!["orphan-daemon".to_owned()];
        let mut buf = String::new();
        for name in &skipped {
            writeln!(buf, "# skipped: no systemd unit for {name}").ok();
        }
        assert!(buf.contains("# skipped: no systemd unit for orphan-daemon"));
        assert!(!buf.contains("[[daemon]]"), "skipped entries must not produce [[daemon]] blocks");
    }

    /// AC5: the generated TOML, when parsed as a fleet config, round-trips cleanly.
    #[test]
    fn generated_toml_round_trips_via_fleet_config() {
        use crate::fleet::FleetConfig;

        let tmp = TempDir::new().expect("tempdir");
        let fleet_path = tmp.path().join("fleet.toml");

        // Build a minimal but complete fleet.toml as fleet-gen would produce.
        let content = r#"
[[daemon]]
name = "wm-audio"
repo = "/home/jsy/wintermute/wintermute-audio"
build_cmd = "cargo build --release"
install_cmd = "cargo install --path . --root ~/.cargo"
launch_cmd = "systemctl --user restart wm-audio.service"
unit = "wm-audio.service"

[[daemon]]
name = "recalld"
repo = "/home/jsy/wintermute/recall"
build_cmd = "cargo build --release"
install_cmd = "cargo install --path . --root ~/.local"
launch_cmd = "systemctl --user restart recalld.service"
unit = "recalld.service"
"#;
        std::fs::write(&fleet_path, content).expect("write fleet.toml");

        let config = FleetConfig::load(&fleet_path).expect("FleetConfig::load must succeed");
        let wm_audio = config.get("wm-audio").expect("wm-audio must be present");
        assert_eq!(wm_audio.unit.as_deref(), Some("wm-audio.service"));

        let recalld = config.get("recalld").expect("recalld must be present");
        assert_eq!(recalld.unit.as_deref(), Some("recalld.service"));

        // validate_names must pass (no missing daemons).
        config
            .validate_names(["wm-audio", "recalld"].iter().copied())
            .expect("validate_names must succeed for known daemons");
    }
}
